### ISSUE TITLE
Feature: Log before function

### ISSUE THREAD

**Issue by DeanAyalon** [pustovitDmytro/logger-decorator#125]
**Please follow the general troubleshooting steps first:**
- I've searched on the [issue tracker](../) before creating one.
- I'm running the latest package version.
- I'm ready to provide help with enhancement if needed.
- Feature will not break current functionality 👍 

**Describe the solution you'd like**
I would actually like two features:
- The main is allowing logger[level] to take in either the function as it currently does, or two functions, 'before' and 'after', like so:
```JavaScript
{ 
    logger: { 
       error: { 
            before: data => {}, 
            after: data => {} 
        }
    }
}
```
So that @log could record both before and after the function is executed

_Edit_
> Maybe it should be a different property entirely, so it can be appended to an existing logger decorator without the need to pass the 'after' function again.

- A 'time' option in the config to measure the runtime of the decorated functions (I believe utilizing console.time should suffice)

**And additionally, I have cloned the repository and made a small fix to two issues, if possible, I'd like to push a branch and make a pull request**

Example:
```JavaScript
@log({
    name: 'appname',
    logger: { 
        info: { 
            before: data => console.log(data.method + ' started', data),
            after: data => console.log(data.method + ' ended', data)
        }
    },
    time: true
})
test = () => console.log('testing') 
```
```Console
test started {
    application: "appname"    // Fixed on my branch 👍 
    <loggerdata, no result/error>
}
testing
test ended {
    application: "appname"
    <loggerdata>
    time: <execution time>    // e.g. 27ms
}
```

Thank you :)

**Comment by pustovitDmytro** [comment]
Hi
1. allowing logger[level] to take in either the function as it currently does, or two functions, 'before' and 'after'

I don't think this API is good because it is impossible to understand whether this should be an `error` or `info` before the function actually runs. Additionally, this will break the "classical" logger API.

I guess something like this would be better:

```javascript
{
    paramsLevel: 'verbose',
    logger: {
        verbose: () => console.log() // Logs are passed here when decorated functions receive params, and params will be added to the payload.
    }
}
```

2. A 'time' option in the config 
A 'time' option in the config is not needed, as there is already a `benchmark` property in the payload, which returns runtime in ms.


3. You can fork and pull request, but read the contributing guide first: [Contributing Guide](https://github.com/pustovitDmytro/logger-decorator/blob/master/.github/CONTRIBUTING.md)

**Comment by pustovitDmytro** [comment]
added `paramsLevel` configuration
